(autoload 'smart-tab-default                    "smart-tab" "" t)
(autoload 'smart-tab                            "smart-tab" "" t)
(autoload 'smart-tab-mode                       "smart-tab" "" t)
(autoload 'global-smart-tab-mode                "smart-tab" "" t)
(provide 'smart-tab-epackage-install)
